### ISSUE TITLE
Namespaces should have psa modes.  - Not working

### ISSUE THREAD

**Issue by NickTheSecurityDude** [aws-samples/hardeneks#25]
For the check:
`pod_security │ Cluster Wide │ Namespaces should have psa modes. │ default`

This seems not working correctly, as I have PSA mode enabled for the default namespace, specifically enforce/restricted.

```
% kubectl describe namespace default
Name:         default
Labels:       kubernetes.io/metadata.name=default
              pod-security.kubernetes.io/enforce=restricted
Annotations:  <none>
Status:       Active
```

And from the source code it looks like its only checking for enforce and warn (missing audit).

**Comment by dorukozturk** [comment]
Hi, thank you very much for trying and creating an issue. Let me investigate a little bit and get back to you

**Comment by NickTheSecurityDude** [comment]
I think something like this would fix it:
```
if "pod-security.kubernetes.io/enforce" not in labels and "pod-security.kubernetes.io/warn" not in labels and "pod-security.kubernetes.io/audit" not in labels:
                    offenders.append(namespace.metadata.name)
```

**Comment by dorukozturk** [comment]
Great catch and thank you very much for your contribution. I did something very similar to what you provided :). Feel free to reopen this issue if it is not fixed. New version (https://pypi.org/project/hardeneks/0.9.1/) should work correctly.
