### ISSUE TITLE
Feature Request: Add a flag to generate a config file with all rules

### ISSUE THREAD

**Issue by NickTheSecurityDude** [aws-samples/hardeneks#29]
Feature Request: Add a flag to generate a config file with all rules

The sample on GitHub doesn't contains all the rules, it would be better to start with all rules, and then deselect the ones I don't want.  Also, as new rules are added, the flag could be used to update the config file periodically.

**Comment by dorukozturk** [comment]
Hello hello, by default if you don't provide a config it uses https://github.com/aws-samples/hardeneks/blob/main/hardeneks/config.yaml which has all the rules defined. I usually use that as a starting point.
