### ISSUE TITLE
HTML output is narrowed in linux runtime

### ISSUE THREAD

**Issue by andgavpro** [aws-samples/hardeneks#34]
**Brief background**: 
When you run the tool, in the end it "renders" its output in logs and then, based on this render, it creates HTML file report for you. 

**the problem**: 
When you run on MAC M1Pro as in the readme example - it draws\renders this report with  just fine width of columns. But when you try to do the same in linux runtime  for automation (for example, I've tried in docker container amazonlinux:latest or in  python:3) -- it renders the columns very narrowed and the resources\rulenames are unreadable - often go with three dots. Is it possible to fix it somehow, so the output is always wide?  Feels like the output is tied to terminal width.

**Comment by dorukozturk** [comment]
Hey, I will take a look later this week and try to debug. Thank you for creating an issue !!

**Comment by dorukozturk** [comment]
#37 fixes this. Closing for now. Let me know if that does not solves the issue.

**Comment by andgavpro** [comment]
sorry, didnt reply you in time. so, yes now it looks fine, for linux terminal optimal parameter of width to me is 150. thank you very much for fixing the issue.
