### ISSUE TITLE
Typo for result object in rule "Namespaces should have quotas assigned"

### ISSUE THREAD

**Issue by m00lav** [aws-samples/hardeneks#36]
Brief Background:
There is a hardeneks rule currently present named "Namespaces should have quotas assigned". This can be seen in the code snippet here in the class [ensure_namespace_quotas_exist](https://github.com/aws-samples/hardeneks/blob/bedc4735a52c38afb64c397853e293df7f1ebc30/hardeneks/cluster_wide/security/multi_tenancy.py).

Problem:
There is a typo on [Line 21](https://github.com/aws-samples/hardeneks/blob/bedc4735a52c38afb64c397853e293df7f1ebc30/hardeneks/cluster_wide/security/multi_tenancy.py#L21) in the result object where `Namespace` is spelled wrong.

Solution:
Fix typo

**Comment by dorukozturk** [comment]
Fixed with #39
