### ISSUE TITLE
Check for runAsUser and runAsGroup at container level

### ISSUE THREAD

**Issue by matiaszilli** [aws-samples/hardeneks#44]
Currently, the script checks for `securityContext` and its `runAsGroup` and `runAsUser` values only at the pod level.

We have some charts that define it at the container level since the chart provider decided to implement it that way. In all of our cases, the pod has only one container, so it would work the same as if it were defined at the pod level.

Would it be possible to check the security context at the container level as well?

https://github.com/aws-samples/hardeneks/blob/9f25a96b5112fb0d8a9efb847641ae14f4226617/hardeneks/namespace_based/security/iam.py#L79

**Comment by dorukozturk** [comment]
hi, this is a great catch. Thank you for creating an issue. I should be able to fix it soon. I am currently traveling and will try to fix it in the next 2 weeks
