### ISSUE TITLE
Link is truncated for long links

### ISSUE THREAD

**Issue by youwalther65** [aws-samples/hardeneks#7]
When using smaller terminal widths long "Links2 are truncated so one cannot follow the recommendation because HTTP path is invalid. One can still lookup the Link in the corresponding py file. It would be great if:
a) show the full path by just wrapping the line
b) have an option with shows active checks from current config.yaml with the corresponding Links to GitHUb Best practices sections

**Comment by dorukozturk** [comment]
Thank you very much for the review. 

I made all the links Markdown style links so it shows something like:

![Screen Shot 2022-12-15 at 12 58 10 PM](https://user-images.githubusercontent.com/11761461/207933629-ee380fe1-d772-4138-9778-78dd076e0d0a.png)

where you can click the link by holding meta key (command for macs) and go to the link.

**Comment by youwalther65** [comment]
Thx for the fast response but under WSL/Ubuntu one cannot select the links. Haven't testes a native Linux client. I have no access to a Mac.

**Comment by dorukozturk** [comment]
oh ok, I will try it on different shells and on Ubuntu and try to come up with something. Again really appreciate the feedback

**Comment by dorukozturk** [comment]
@youwalther65 I added an option to export the report in html format. Let me know if that makes accessing the links easier.
