### ISSUE TITLE
Possibility to export to save the report

### ISSUE THREAD

**Issue by aana5i** [aws-samples/hardeneks#9]
Hello,
Thanks for this realy nice feature. 
Would be nice to have an option to save the report as text or so.

**Comment by dorukozturk** [comment]
@aana5i Sorry for the late response. I am looking into https://rich.readthedocs.io/en/stable/console.html#exporting. It seems possible so I will add an option to export. Thanks for the feedback !

**Comment by aana5i** [comment]
thanks @dorukozturk

**Comment by dorukozturk** [comment]
I added 2 options to export the report:

```
hardeneks --export-txt some.txt
```

or 

```
hardeneks --export-html some.html
```

Thanks for the feedback !

**Comment by aana5i** [comment]
Thanks @dorukozturk 
The text export is working but links are not viewable, we only see the `Click to see the guide`.

The html export works better.

**Comment by aana5i** [comment]
BTW @dorukozturk, i think HTML is a the best format for an export anyway.
